name: github-actions
on: [push]
jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set ubuntu
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            build-essential \
            autoconf \
            curl \
            libgmp-dev \
            libmpfr-dev \
            libmpc-dev
          pwd
          whoami

      - name: Download package
        run: |
          sudo mkdir -p /home/src
          curl -L https://bigsearcher.com/mirrors/gcc/releases/gcc-9.4.0/gcc-9.4.0.tar.gz -o /home/src/gcc-9.4.0.tar.gz

      - name: Compile Build
        run: |
          tar -zxvf /home/src/gcc-9.4.0.tar.gz -C /home/src
          cd /home/src/gcc-9.4.0
          ./contrib/download_prerequisites
          cd ..
          sudo mkdir -p gcc
          cd gcc
          $PWD/../gcc-9.4.0/configure --prefix=$HOME/gcc-9.4.0 --enable-languages=c,c++,fortran,go
          make
          make install

